version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: secure-lock-kubernetes.svg
  required:
    - build
    - repo
  info:
    git url: >-
      [https://github.com/hmagph/simple-knative-toolchain](https://github.com/hmagph/simple-knative-toolchain)
    git branch: >-
      [master](https://github.com/hmagph/simple-knative-toolchain/tree/master)
toolchain:
  name: 'knative-toolchain-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted" 
services:
  repo:
    service_id: github_integrated
    parameters:
      repo_name: 'hello-helm-{{timestamp}}'
      repo_url: 'https://github.ibm.com/philippe-mulet/sample'
      type: link
      has_issues: true
      enable_traceability: false
  build:
    service_id: customtool
    parameters:
      type: Delivery Pipeline Knative
      lifecyclePhase: "DELIVER"
      imageUrl: https://raw.githubusercontent.com/knative/docs/master/images/logo/rgb/knative-logo-rgb.png
      documentationUrl: 
      name: simple-pipeline
      dashboard_url: http://localhost:4000/pipelines/simple-pipeline/runs/latest
      description: Knative pipeline
      additional-properties: 
  webide:
    service_id: orion

